"""
sql_generator.py

Send schema mapping information to Claude to create migration SQL.
Steps 1 and 4 are built from Python templates using METADATA_TABLES.
Steps 2 and 3 are generated by Claude, which receives METADATA_TABLES as context.
"""
import json
import anthropic
from dotenv import load_dotenv

load_dotenv()

# Single source of truth for migration_metadata table schemas.
# Changing a column here updates both the generated DDL and the Claude context automatically.
METADATA_TABLES = {
    "pre_migration_counts": {
        "columns": [
            ("snapshot_id",       "SERIAL PRIMARY KEY"),
            ("table_name",        "VARCHAR(200) NOT NULL"),
            ("row_count",         "BIGINT NOT NULL"),
            ("snapshot_taken_at", "TIMESTAMPTZ NOT NULL DEFAULT now()"),
        ],
    },
    "key_mapping": {
        "columns": [
            ("mapping_id", "SERIAL PRIMARY KEY"),
            ("table_name", "VARCHAR(200) NOT NULL"),
            ("source_key", "VARCHAR(50)  NOT NULL"),
            ("target_key", "INTEGER      NOT NULL"),
            ("created_at", "TIMESTAMPTZ  NOT NULL DEFAULT now()"),
        ],
        "constraints": ["CONSTRAINT key_mapping_unique UNIQUE (table_name, source_key)"],
    },
    "migration_log": {
        "columns": [
            ("log_id",        "SERIAL PRIMARY KEY"),
            ("table_name",    "VARCHAR(200) NOT NULL"),
            ("rows_inserted", "BIGINT       DEFAULT 0"),
            ("status",        "VARCHAR(50)  NOT NULL"),
            ("message",       "TEXT"),
            ("logged_at",     "TIMESTAMPTZ  NOT NULL DEFAULT now()"),
        ],
    },
    "validation_results": {
        "columns": [
            ("validation_id",  "SERIAL PRIMARY KEY"),
            ("check_name",     "VARCHAR(300) NOT NULL"),
            ("expected_value", "TEXT"),
            ("actual_value",   "TEXT"),
            ("passed",         "BOOLEAN      NOT NULL DEFAULT false"),
            ("checked_at",     "TIMESTAMPTZ  NOT NULL DEFAULT now()"),
        ],
    },
}


def _generate_metadata_ddl():
    """Generate CREATE TABLE IF NOT EXISTS statements from METADATA_TABLES."""
    statements = []
    for table_name, defn in METADATA_TABLES.items():
        col_defs    = [f"    {col:<18} {dtype}" for col, dtype in defn["columns"]]
        constraints = [f"    {c}" for c in defn.get("constraints", [])]
        body        = ",\n".join(col_defs + constraints)
        statements.append(
            f"CREATE TABLE IF NOT EXISTS migration_metadata.{table_name} (\n{body}\n);"
        )
    return "\n\n".join(statements)


def _metadata_schema_summary():
    """Compact one-liner per table passed to Claude — ensures correct column names in INSERTs."""
    lines = []
    for table_name, defn in METADATA_TABLES.items():
        cols = ", ".join(col for col, _ in defn["columns"])
        lines.append(f"  migration_metadata.{table_name}({cols})")
    return "\n".join(lines)


def _slim_mapping(mapping_result):
    """Strip fields not needed for SQL generation to reduce input tokens."""
    return {
        "overall_risks": mapping_result.get("overall_risks", []),
        "table_mappings": [
            {
                "source_table": tm["source_table"],
                "target_table": tm["target_table"],
                "column_mappings": [
                    {
                        "source_column":       cm["source_column"],
                        "target_column":       cm["target_column"],
                        "source_type":         cm["source_type"],
                        "target_type":         cm["target_type"],
                        "transformation_needed": cm["transformation_needed"],
                        "transformation_note": cm.get("transformation_note"),
                    }
                    for cm in tm["column_mappings"]
                ],
            }
            for tm in mapping_result["table_mappings"]
        ],
    }


def build_prerequisites_sql(mapping_result):
    """Generate Step 1 (prerequisites) as a Python template — no Claude call."""
    source_tables = ", ".join(tm["source_table"] for tm in mapping_result["table_mappings"])

    warnings = []
    for risk in mapping_result.get("overall_risks", []):
        risk_lower = risk.lower()
        if any(kw in risk_lower for kw in ("no target", "unmapped", "orphan", "no mapping", "no corresponding", "no equivalent", "not migrated", "has no target")):
            warnings.append(f"-- WARNING: {risk}")
    warnings_block = ("\n" + "\n".join(warnings) + "\n") if warnings else ""

    return f"""\
-- ============================================================
-- STEP 1: PREREQUISITES (Execute on: TARGET)
-- ============================================================
{warnings_block}
CREATE EXTENSION IF NOT EXISTS postgres_fdw;

-- TODO: Replace placeholder values with actual SOURCE connection details before running
CREATE SERVER IF NOT EXISTS source_server
    FOREIGN DATA WRAPPER postgres_fdw
    OPTIONS (
        host   'sourcehost',    -- TODO: actual SOURCE host
        port   'sourceport',    -- TODO: actual SOURCE port
        dbname 'sourcedbname'   -- TODO: actual SOURCE dbname
    );

CREATE USER MAPPING IF NOT EXISTS FOR CURRENT_USER
    SERVER source_server
    OPTIONS (
        user     'sourceuser',      -- TODO: actual SOURCE user
        password 'sourcepassword'   -- TODO: actual SOURCE password
    );

CREATE SCHEMA IF NOT EXISTS source_schema;

IMPORT FOREIGN SCHEMA public
    LIMIT TO ({source_tables})
    FROM SERVER source_server
    INTO source_schema;

CREATE SCHEMA IF NOT EXISTS migration_metadata;

{_generate_metadata_ddl()}
"""


def build_post_migration_sql(mapping_result):
    """Generate Step 4 (post-migration) as a Python template — no Claude call."""
    table_pairs   = [(tm["source_table"], tm["target_table"]) for tm in mapping_result["table_mappings"]]
    target_tables = [tm["target_table"] for tm in mapping_result["table_mappings"]]

    # Sequence resets — dynamically find serial columns at runtime per target table
    seq_resets = "\n".join(
        f"""\
DO $$
DECLARE r record;
BEGIN
    FOR r IN
        SELECT a.attname
        FROM pg_attribute a
        WHERE a.attrelid = '{tbl}'::regclass
          AND a.attnum > 0 AND NOT a.attisdropped
          AND pg_get_serial_sequence('{tbl}', a.attname) IS NOT NULL
    LOOP
        EXECUTE format(
            'SELECT setval(%L, COALESCE((SELECT MAX(%I) FROM {tbl}), 1))',
            pg_get_serial_sequence('{tbl}', r.attname), r.attname
        );
    END LOOP;
END $$;"""
        for tbl in target_tables
    )

    # Row count validation — one INSERT with UNION ALL across all table pairs
    union_parts = "\n    UNION ALL\n    ".join(
        f"""\
SELECT 'Row count: {tgt} vs {src}',
       pmc.row_count::text,
       (SELECT COUNT(*) FROM {tgt})::text,
       (SELECT COUNT(*) FROM {tgt}) = pmc.row_count,
       now()
FROM migration_metadata.pre_migration_counts pmc
WHERE pmc.table_name = '{src}'"""
        for src, tgt in table_pairs
    )

    return f"""\
-- ============================================================
-- STEP 4: POST-MIGRATION VALIDATION (Execute on: TARGET)
-- ============================================================

SET CONSTRAINTS ALL IMMEDIATE;

-- Reset sequences to prevent PK collisions on future inserts
{seq_resets}

-- Row count validation
INSERT INTO migration_metadata.validation_results
    (check_name, expected_value, actual_value, passed, checked_at)
    {union_parts};

-- Final validation summary
SELECT check_name, expected_value, actual_value, passed, checked_at
FROM   migration_metadata.validation_results
ORDER  BY checked_at, check_name;

-- Migration log summary
SELECT table_name, rows_inserted, status, message, logged_at
FROM   migration_metadata.migration_log
ORDER  BY logged_at;
"""


def generate_migration_sql(mapping_result):
    """
    Generate a complete migration script.
    Steps 1 and 4 are built from METADATA_TABLES — no Claude call.
    Steps 2 and 3 are generated by Claude using METADATA_TABLES as context.
    """
    client = anthropic.Anthropic()
    slim   = _slim_mapping(mapping_result)

    prompt = f"""You are a data engineering expert executing a database migration.
Generate ONLY Steps 2 and 3 below — Steps 1 and 4 are handled separately.

CONNECTION RULE:
- All SQL is executed on the TARGET database only.
- SOURCE data is accessed exclusively through source_schema (postgres_fdw).
- All tracking and logging goes into migration_metadata schema.

METADATA TABLES (already created — use these exact column names in all INSERTs):
{_metadata_schema_summary()}
Never include SERIAL/auto-increment columns (snapshot_id, mapping_id, log_id, validation_id) in INSERT column lists.

MAPPING:
{json.dumps(slim, indent=2)}

-- STEP 2: PRE-MIGRATION VALIDATION (Execute on: TARGET) --
Generate only this — nothing else:
Row count snapshots — ONE INSERT with UNION ALL across all source tables into migration_metadata.pre_migration_counts
Do NOT add referential integrity checks, format checks, range checks, or any INSERT into migration_metadata.validation_results.

-- STEP 3: MIGRATION (Execute on: TARGET) --
1. SET CONSTRAINTS ALL DEFERRED
2. For any source string PK that maps to a target integer PK: INSERT into migration_metadata.key_mapping using ROW_NUMBER() OVER (ORDER BY source_pk); store the TARGET table name in key_mapping.table_name and JOIN on that same name when reading back
3. For any table with a self-referential FK: two-pass approach — Pass 1 inserts all rows with that column set to NULL; Pass 2 UPDATEs it via key_mapping; log Pass 2 with rows_inserted = NULL
4. For each table mapping, one INSERT INTO ... SELECT with no blank lines between SELECT columns
5. After each INSERT (and each Pass 2 UPDATE), one INSERT into migration_metadata.migration_log

Output format rules:
- No SQL comments of any kind — no sub-headers, no dashes, no labels — except the two section markers (-- STEP 2: ... and -- STEP 3: ...)
- Write every CASE expression on a single line
- One blank line between complete SQL statements; zero blank lines inside a statement

PostgreSQL typing rules:
- Only cast where types genuinely differ (e.g. varchar→date, varchar→integer, char→boolean, timestamp→timestamptz)
- Always wrap TO_DATE() with NULLIF: TO_DATE(NULLIF(TRIM(col), ''), 'YYYY-MM-DD')
- In recursive CTEs and UNION ALL, cast columns to match the first term's types
- Cast ARRAY constructors explicitly: ARRAY[col]::type[]

Return ONLY the SQL code. Use PostgreSQL syntax."""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=16384,
        messages=[{"role": "user", "content": prompt}],
    )

    if message.stop_reason == "max_tokens":
        raise RuntimeError("Claude response was truncated. Increase max_tokens further.")

    response_text = message.content[0].text

    if "```sql" in response_text:
        response_text = response_text.split("```sql")[1].split("```")[0]
    elif "```" in response_text:
        response_text = response_text.split("```")[1].split("```")[0]

    step1 = build_prerequisites_sql(mapping_result)
    step4 = build_post_migration_sql(mapping_result)

    return step1 + "\n" + response_text.strip() + "\n\n" + step4


def save_migration_sql(sql_text, output_path):
    """Save generated SQL to a file."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated migration SQL\n")
        f.write("-- Generated by Schema Mapping Assistant\n")
        f.write("-- Review carefully before executing\n\n")
        f.write(sql_text)
    print(f"Migration SQL saved to: {output_path}")